version: "2"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
